### ISSUE TITLE
release.sh dovrebbe cambiare la versione anche n CITATION.cff

### ISSUE THREAD

**Issue by jbogdani** [lab-archeologia-digitale/directus-extension-harris-matrix#9]
Con l'aggiunta di [CITATION.cff](https://github.com/lab-archeologia-digitale/directus-extension-harris-matrix/blob/main/CITATION.cff) ([per info](https://lad.saras.uniroma1.it/blog/sistema-citazione-bibliografica-per-github/)) è necessario che il workflow di release aggiorni anche questo, per non creare confusione con i numeri di versione.

**Comment by domesantoro** [comment]
Done!

Sono state create alcune versioni virtuali (abbiamo brucato fino a v2.0.19) per testare le automazioni
